/vis/open HepRepFile
/vis/drawVolume
/vis/viewer/flush

/vis/modeling/trajectories/create/generic
/vis/modeling/trajectories/generic-0/default/setLineColour green
/vis/modeling/trajectories/generic-0/default/setDrawLine true
/vis/modeling/trajectories/generic-0/default/setDrawAuxPts true
/vis/modeling/trajectories/generic-0/default/setDrawStepPts true
/vis/modeling/trajectories/generic-0/default/setStepPtsSize 5
/vis/modeling/trajectories/generic-0/default/setAuxPtsSize 5
/vis/modeling/trajectories/generic-0/default/setAuxPtsColour yellow
/vis/modeling/trajectories/generic-0/default/setStepPtsColour red
/vis/modeling/trajectories/generic-0/default/setStepPtsColour red
/vis/modeling/trajectories/generic-0/default/setStepPtsType circles

/vis/scene/add/trajectories rich
/vis/scene/add/hits

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma red
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
/vis/modeling/trajectories/drawByParticleID-0/set proton cyan

/vis/verbose quiet

#comment this for single heprep file per event
/vis/scene/endOfEventAction accumulate

/vis/disable

/run/beamOn -1

/vis/enable
/vis/reviewKeptEvents
